- org/ios.ts
I made a change on the WPiOS Podfile to simplify handling gutenberg references.
Those changes broke the gutenberg exception.
This is how the Podfile looks:
https://github.com/wordpress-mobile/WordPress-iOS/blob/cbed6c40bed0e1bfc3f1de918cfb81d008512ea4/Podfile#L104
If this is not the best way and is better to bring back the `:git => ...` reference to that line, please let me now and I'll do that. Otherwise I hope the change in this PR will fix the gutenberg `:commit => ...` exception.
> Update gutenberg commit hash expection on iOS Podfile

- org/android.ts
- org/ios.ts
I noticed that the release notes check fails on the WooCommerce apps because they use .pot files instead of .po. 
I'm also not sure how we can test it.
> Make release notes checks work with .po and .pot files

- .circleci/config.yml
- package.json
- yarn.lock
This PR adds a CircleCI config to run our newly added jest tests on CircleCI (https://github.com/Automattic/peril-settings/pull/7).
It also updates `package.json` with a new dependency to support this and updates the licence to remove a warning.
See that CircleCI has successfully run the tests on this PR.
cc @markpar
> Run tests on CircleCI

- org/github/check-login-subtree.ts
- peril-settings.json
- tests/check-login-subtree.test.ts
This is a quick follow up to the work @markpar did in https://github.com/Automattic/peril-settings/pull/7.
I've made these two changes:
- Post the `libs/login` instructions as a message instead of a warning. This isn't always an error case (e.g. release branches) so I think that is more suitable.
- Add the check to WCAndroid now that it has been working reliably 😄
> Update libs/login check and add to WooCommerce-Android

- org/github/check-login-subtree.ts
Adds a warning to the subtree push instructions message reminding the reader that versions of git from `2.20` and up currently shouldn't be used for subtree operations.
> Add warning about git version to subtree message

- .circleci/config.yml
This adds a small `Restart` job to CircleCI that runs on `master` to restart the Heroku apps for each org. It means we are always using the latest settings. This wouldn't be needed if the peril settings weren't shared between orgs (see https://github.com/danger/peril/issues/440#issuecomment-510932197).
> CircleCI: Restart Heroku on push to master

- org/pr/android-installable-build.ts
- package.json
- peril-settings.json
- tests/android-installable-build-test.ts
- yarn.lock
Adds a Peril event that will post a comment on Android PRs with an APK to test. You can see an example of this working [here](https://github.com/wordpress-mobile/WordPress-Android/pull/10404#issuecomment-522626257). Screenshot:
It does this by using the `status.success` webhook as follows:
- If the status check is for a CircleCI build called `Installable Build`, use the CircleCI API to check for APK artifacts.
- Post a comment (or update the existing one) to the PR with a link to download the APK.
> Post comment with APK link on Android PRs with installable builds

- peril-settings.json
This opts WooCommerce Android into the behaviour added in https://github.com/Automattic/peril-settings/pull/14.
WCAndroid PR is here: https://github.com/woocommerce/woocommerce-android/pull/1387
> Add installable build support to WCAndroid

- peril-settings.json
This is a tiny change to enable the existing installable build handling (reviewed in https://github.com/Automattic/peril-settings/pull/14) to Simplenote Android.
The companion PR is 
We can't really test this until it is merged, but since its already in use for WCAndroid and WPAndroid there isn't any risk involved.
> Add installable builds to Simplenote Android

- peril-settings.json
This is a tiny change to enable the existing installable build handling (reviewed in https://github.com/Automattic/peril-settings/pull/14) to Portkey Android.
The companion PR is https://github.com/Automattic/portkey-android/pull/179.
We can't really test this until it is merged, but since its already in use for WCAndroid, WPAndroid and Simplenote Android there isn't any risk involved.
> Add installable builds to Portkey

- org/pr/force-circleci-status.ts
- peril-settings.json
- tests/force-circleci-status-test.ts
We would like to start taking advantage of CircleCI's [approval feature](https://circleci.com/docs/2.0/workflows/#holding-a-workflow-for-a-manual-approval) so that we can avoid running resource-intensive jobs on every push.
The problem with this is that jobs pending approval show as in progress status checks on Github, which is confusing and misleading. For example, I have added a job pending approval in https://github.com/wordpress-mobile/WordPress-iOS/pull/12654. This is what the PR looks like:
This adds a small action to Peril to look for a list of statuses with a specific label (e.g. `ci/circleci: Installable Build/Hold`) in the pending state and use the Github API to mark is as successful.
It is difficult to test this without deploying but once the tests are passing I think its safe.
> Add new action to force pending commit statuses to be successful

- org/pr/check-tracks.ts
- peril-settings.json
- tests/check-tracks-test.ts
This PR adds a `check-tracks` rule that publishes a comment when changes related to `Tracks` are detected. 
The rule is theoretically general, but given the hardcoded file names, it's going to run only for WooCommerce Android.
> Add rule to check for Tracks related changes.

- peril-settings.json
This is just a quick opt-in for WCiOS to support installable builds. Until its implemented, it will just do nothing, so no risk here.
> Run installable builds rule for WCiOS

- peril-settings.json
Adds a new setting to support installable builds in Newspack iOS.
> Adds peril settings for Newspack iOS

- org/pr/installable-build.ts
I'm trying to figure out an issue where the `comment.json` is uploaded to CircleCI and has the right format, but it's discarded/not found by Peril, so this PR adds some debug messages to the console.
This is intended to be reverted as soon as the issue is fixed.
> Add temp debug stuff

- org/pr/check-tracks.ts
- org/pr/installable-build.ts
This PR:
- reverts the additional logging added to debug this issue (but still adds a log entry in a critical point). 
- removes a call to an API that doesn't actually seem to be in the Danger DSL. It was added here: https://github.com/Automattic/peril-settings/commit/0c7b962a56db5a478b6d9beeb498f4f2a1c830ae#diff-e03db42699566c628c96cd4785dde689, but I can't find a reference to it in the DSL: https://danger.systems/js/reference.html#DangerDSLType. Note that this fixes the tests, but only because the endpoint was not mocked. If I'm wrong and the endpoint exists, the proper fix would be to add it to the mocked object.
- adds the auth token to the API call to download artifacts. 
As usual with this repo, there's no easy way to test this. 
I tested locally with an ad-hoc JS script and it …
> Fix artifacts download on private repos

- peril-settings.json
This PR enables Installable Builds for Simplenote iOS. 
There's no easy way to test it, but as long as the JSON syntax is correct, it shouldn't break anything.
> Enable Installable builds for Simplenote iOS

- README.md
Makes the README a bit more informative, loosely inspired by https://gist.github.com/PurpleBooth/109311bb0361f32d87a2.
> Add instructions on how to build and run the tests

- org/pr/ios-macos.ts
This PR is an attempt to fix the "Cannot read property 'labels' of undefined" we've been seeing lately. 
Since it looks like the `labels` property sometimes isn't available after some time, this PR tries to get it when the action is triggered. 
I'm not totally sure this will fix the issue, but based on experiences we had with similar issues in the past, it _may_ do the trick.
> Fix the "cannot read property 'labels' of undefined" error

- org/pr/optional-tests.ts
- tests/optional-tests-test.ts
This change is based on the existing Installable Build setup, to support optional test runs on PRs. This PR makes the following changes:
* Forces a `success` status for `Optional Tests/Hold` checks on PRs (so the check doesn't remain in pending status on the PR).
* Posts a comment to the PR with a link to the CircleCI workflow, so the optional tests can be started. Comment text: "You can trigger optional UI/connected tests for these changes by visiting CircleCI here."
* Adds tests for these changes to this repo.
Once the `Optional Tests/Hold` job is started, any jobs that rely on it (i.e. the optional UI/connected tests) will start running and report the test results on the PR.
> Post comment with link to trigger optional tests on PRs

- peril-settings.json
This enables the optional tests changes from https://github.com/Automattic/peril-settings/pull/39 in the `wordpress-mobile/WordPress-Android` and `wordpress-mobile/WordPress-iOS` repos.
To test: Confirm tests pass.
> Enable optional tests comment in WordPress repos

- org/pr/optional-tests.ts
This PR adds another CircleCI status to process for the Optional Tests settings in `/org/pr/optional-tests.ts`. This is due to the CircleCI workflow setup on iOS, for example in https://github.com/wordpress-mobile/WordPress-iOS/pull/13785.
> Update optional tests settings for WPiOS

- org/pr/gb-mobile-ui-tests.ts
- peril-settings.json
- tests/gb-mobile-ui-tests-test.ts
This change is based on the existing `Optional Tests/Hold` changes from https://github.com/Automattic/peril-settings/pull/39. The intention behind it is to enable optional test runs for https://github.com/wordpress-mobile/gutenberg-mobile.
> Post comment to trigger UI tests for gb-mobile

- org/pr/check-subtrees.ts
- tests/check-subtrees.test.ts
We have agreed to stop trying to share WordPressMocks between WPAndroid and WPiOS (internal ref: paaHJt-PH-p2). For now we will continue to use the `wordpress-mobile/WordPressMocks` repo as the iOS mocks pod and let WPAndroid diverge from it.
The changes in this PR will allow WPAndroid to diverge by removing the reminder to merge mocks changes upstream.
To test: Confirm changes look reasonable and tests pass.
> Update subtree check to remove check for WordPressMocks changes

- peril-settings.json
This enables the optional tests setup in the `woocommerce/woocommerce-ios` repo.
You can see an example PR that would use this setup (with the check `ci/circleci: Optional Tests/Hold`) here: https://github.com/woocommerce/woocommerce-ios/pull/2214
> Enable optional tests for WooCommerce iOS

- org/pr/check-subtrees.ts
- tests/check-subtrees.test.ts
I've recently updated the `WordPress-Utils-Android` library with the changes from WPAndroid in https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/27. Since we didn't have a peril check to remind developers, the utils library was very outdated. This PR adds this check, so this won't happen again.
> Adds subtree checks for libs/utils

- tsconfig.json
My Vim plugin for JSON shows syntax violations.
[JSON doesn't support trailing commas](https://www.json.org/json-en.html), even though most parsers can deal with it.
Really, this is only so I don't see red warnings when opening this file 😅
> Use JSON syntax complying to spec in tsconfig.json

- org/pr/milestone.ts
- tests/pr-milestone.test.ts
This PR disables the milestone check in certain conditions. If the PR is a draft, we always skip the check. This should give developers more flexibility for when they are actively working on a PR. There is now an optional label `Part of a WIP Feature` which will only disable the check if the base branch is **not** `develop` or `release/{version}`.
Disabling this check for wip features was something requested by developers and @elibud gave 👍 as long as it doesn't affect regular PRs. Since a PR needs to be merged to `develop` or a release branch before it can be shipped, I can't think of a scenario where we might miss this check with this setup. I am even questioning whether the extra label is necessary and if we should just disable the milestone checks for PRs unless they are being merged …
> Disable milestone check for draft PRs and wip features

- org/pr/milestone.ts
We started to have some [weird errors](https://github.com/wordpress-mobile/WordPress-Android/pull/12082#issuecomment-637726639) since we merged #49. @jkmassel pointed out that some `danger` objects might be dropped during the `await` operation and historically our approach to this weird problem has been to use a bunch of `const` values at the top. So, hopefully this PR will help.
> Assign necessary values to consts for milestone check

- org/pr/ios-macos.ts
- tests/ios-macos.test.ts
This PR removes the exception for Gutenberg when checking that the pods are referenced by version. 
To Test:
- Check that CI is green.
> Remove Gutenberg exception when checking pod references on iOS

- org/pr/android-library.ts
- peril-settings.json
- tests/android-library.test.ts
Adds a rule to make sure that every PR towards `develop` or `trunk` in Android libraries bumps the library version.
You can test this using the instructions in https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/49.
> Add rule to check that PRs in Android libraries update the version

- org/pr/release-notes.ts
- peril-settings.json
- tests/release-notes-test.ts
I've noticed that sometimes changes to RELEASE-NOTES.txt are merged into the release branch thinking they will be reflected in the final release notes. Due to how our current flow for translations works, this is not the case and a manual update is required in order to try to update the release notes after the code freeze. 
This PR introduces a new check that prints a warning on PRs that:
-  target the release branch, and 
- contain changes to RELEASE-NOTES.txt. 
To Test:
Testing changes to Peril rules is not easy. Because of this I've added some tests to cover the most common cases. 
- Make sure CI is green. 
- Verify that the mocked API responses match the actual GitHub API.
> Add checks for changes to the release notes in a release branch

- peril-settings.json
I noticed Peril wasn't commenting with links to installable builds on PRs in https://github.com/Automattic/stories-android/ anymore. It seemed like it had started around the time we renamed the repository from `portkey-android`, and it looks like that's because the reference in `peril-settings` needed to be updated.
I imagine this change is all that's needed to get that working again, but please let me know if I need to do anything else!
For reference, this PR originally added support for installable builds to the stories repo: https://github.com/Automattic/stories-android/pull/179
> Update stories repository to reflect renaming

- org/pr/check-subtrees.ts
- tests/check-subtrees.test.ts
This PR is a follow up to https://github.com/wordpress-mobile/WordPress-Android/pull/13466 and should be merged after that one. 
It simply removes the checks we do on changes on subtrees for the WPUtils library, because the library is not going to be a subtree anymore.
> Remove subtree checks for WPUtils

- org/pr/optional-tests.ts
- tests/optional-tests-test.ts
This PR adds `fluxc/Optional Tests` to hold contexts so we can mark them as green. It also improves the unit tests for this so multiple contexts can be tested.
I suggest utilizing the `Hide whitespace changes` option for the diff as most of the changes are for indentation level change.
> Add fluxc/Optional Tests

- peril-settings.json
Since we are currently only interested in marking optional tests as green as implemented in #62, I thought only adding the `status` property would be enough. Admittedly I don't know anything about this json, so I just made an educated guess using the information about the other repos.
> Adds WordPress-FluxC-Android repo to peril settings

- org/pr/android.ts
- tests/android-test.ts
This PR fixes two bugs with the Android translatable strings check: 
- It fixes string interpolation in the warning message.
- It fixes the string pattern that the check uses (and the related tests). 
**To Test:**
Changes to Peril rules can't be easily tested, so: 
- Check that the code changes look good. 
- Check that CI is green.
> Fix Android translatable strings check

- org/pr/milestone.ts
- tests/pr-milestone.test.ts
This PR adds a new check on milestones which warns when a milestone is assigned _or_ the PR is modified at a time close to the milestone's due date. 
The initial idea was to post the warning only when a milestone is assigned, but there's no way to get the previous state on Peril, so we can't know the action which triggered Peril.
Anyway, I think that having the warning published also on PRs that are worked on the last days of the cycle has a value. 
There's no easy way to test these changes, so I added some tests based on the [GitHub API documentation](https://docs.github.com/en/rest/reference/issues).
> Add warning on soon-closing milestones

- org/pr/milestone.ts
- tests/pr-milestone.test.ts
This PR fixes an issue with the `milestone` rule where the warning about having set a milestone which is close to its due date is triggered also on merges. 
Looking at [GitHub documentation](https://docs.github.com/en/rest/reference/pulls), the state of a PR is set to `closed` when a PR is closed or merged, so checking for `state == "merged"` should cover both cases.
> Avoid warning about soon to close milestones on merged PRs

- package.json
- yarn.lock
This upgrades the following, in an attempt to fix [all the recent Dependabot alerts](https://github.com/Automattic/peril-settings/security/dependabot) at once:
- `danger` from `8.x` to `10.x`
- `jest` (tooling for js/typescript unit testing) and its related dependencies
- Ran `yarn outdated` to check the latest versions of all dependencies
- I've looked at [Danger's CHANGELOG](https://github.com/danger/danger-js/blob/main/CHANGELOG.md) and especially the changes between major version bumps.
- The only breaking change that is listed is `JSONDiffForFile` when bumping to `9.x` to `10.x`, and we don't seem to use that in our rules, so we should be good to do a major version bump here
- Updated the `package.json` with the latest versions for `danger` + for `jest` & friends
- Ran `yarn install` …
> Upgrade yard dependencies

- org/pr/installable-build.ts
- tests/installable-build-test.ts
With the recent changes related to the Jetpack app, Peril stopped to update the `Installable Build` comment on PRs. The root cause of the issue is that the job name used for the WordPress and Jetpack installable builds now contains the app name and, so, the status reported by CircleCI doesn't match the expected one anymore. 
Peril expects a `success` status with `ci/circleci: Installable Build` as the context, but the new context is either `"ci/circleci: WordPress Installable Build"` or `"ci/circleci: Jetpack Installable Build"`.
This PR fixes the issue by using regex for the expected statuses.
> Fix installable build comments on custom statuses

- org/pr/installable-build.ts
- tests/installable-build-test.ts
The link in the Peril comment for the installable WPAndroid build (e.g https://github.com/wordpress-mobile/WordPress-Android/pull/14936#issuecomment-868401819) is actually pointing to the Jetpack app.
We're able to download the apk if we visit the artifacts page anyway, but it's nicer to have Peril provide the link for all installable APKs not just the first one.
\cc @hypest
> Handle multiple APKs installable for an Installable Build

- org/pr/optional-tests.ts
- peril-settings.json
- tests/optional-tests-test.ts
While working [on a small PR on Simplenote iOS](https://github.com/Automattic/simplenote-ios/pull/1318) I noticed that the status of Optional Tests which are on hold is not green. 
This PR adds the Simplenote iOS Optional Tests to the list of jobs which PR updates to avoid that the status of the PR never goes green.
> Update optional tests state for Simplenote-iOS

- org/pr/android-diff-size.ts
It looks like we are still experiencing the issue/bug/glitch where some properties sometimes become unavailable during the flow. This PR applies the workaround we found for this problem to the new Android Diff Size rule.
> Workaround to fix a glitch in Android diff size 

- peril-settings.json
While looking at p1629260121056500-slack-C02QANACA I noticed that we ran all our main Danger rules on _every_ action of the `pull_request` event, while some of them only make sense to be run on specific ones.
- In particular, we run those rules even on actions like `pull_request.closed` while at that stage there's no need to re-run Danger.  
- We also re-run rules that run checks on certain things that couldn't have been changed by certain events, e.g. we tested the labels even on new commits pushed on the PR without any label change, or re-checked the release notes or the diff size even just when the only thing that triggered the webhook was a label being added, etc.
As a result, we ended up having Danger/Peril failures from time to time, due:
- Either to glitches in the API that made …
> Update peril-settings to reduce GitHub API calls

- org/pr/android.ts
- peril-settings.json
The recent PR https://github.com/Automattic/peril-settings/pull/84 accidentally merged the settings for `issue/labels.ts` and `pr/labels.ts` into a single set of events all related to Pull Requests only, resulting in the `Please add a type label to this issue. e.g. '[Type] Enhancement'` message from the `issue/labels.ts` rule now appearing in all `Releases` PRs (example [here](https://github.com/wordpress-mobile/WordPress-Android/pull/15228#issuecomment-903180621))
We thus missed the fact that there are actually two different rules for labels, one for issue and one for PR, and they still need to be kept on separate triggers.
---
In addition, I also:
- added the `labeled`/`unlabeled` event triggers on the diff and release-notes rules as they both depends on which labels are set (and make …
> Fix rule settings for labels

- org/pr/optional-tests.ts
- tests/optional-tests-test.ts
This PR revert "Add Jetpack-specific hold contexts for tests" which should fix a weird behaviour on Optional Tests for WPiOS.
> Fix WPiOS optional tests

- org/pr/installable-build.ts
- tests/installable-build-test.ts
After https://github.com/Automattic/peril-settings/pull/89 got merged, I've started noticing that the status of the `Installable Build` job for the Jetpack application doesn't get updated from `pending (orange)` to `ready (green)`. 
The reason is that [this commit](https://github.com/Automattic/peril-settings/commit/1ed4cc4df9518037fc2287fd0278c15aace56c9d) removed it from the list of the handled states. 
My understanding, from the commit title, is that the goal was to avoid that Peril commented on the PR with the prompt to run the installable build for Jetpack.
I think we still want the state of the job to be green, because, otherwise, the PR remains in a pending state and, while it's still possible to merge the changes because the job is not required, this behaviour can create …
> Update the Installable Build job status for Jetpack

- org/pr/optional-tests.ts
- tests/optional-tests-test.ts
This should fix the `Pending` "ci/circleci: Optional UI Tests/Hold" for WCAndroid.
> Adds 'ci/circleci: Optional UI Tests/Hold' to optional-tests

- peril-settings.json
In #96, I missed that `optional-tests` wasn't added to WCAndroid repo, so unfortunately that change alone wasn't enough.
> Adds optional-tests to WCAndroid repo

- org/pr/milestone-woo.ts
- peril-settings.json
Since we recently moved to 1-week release cycles and milestones matching these releases, we always get those warnings if we assign the PR to the next milestone (which happens often) because it is always closing in less than 4 days. That adds too much noise and loses the original intent of those warnings. Because of that, we decrease the warning days to two with this PR.
> Internal Ref: pdnsEh-B2-p2
- Create a new milestone file for woo with 2 warning days
- Point to that file in the peril settings json for woo ios and android
> Decrease Woo PR Milestone Warning days

- org/pr/label.ts
- tests/pr-label.test.ts
WPAndroid repos use a different name for that kind of label, with 'not ready for merge' rather than 'do not merge' wording, so we have to take that into account too.
---
This is to prevent the case of accidental merge of https://github.com/wordpress-mobile/WordPress-Android/pull/17581#issuecomment-1332383754 I did earlier today — and had to revert later in https://github.com/wordpress-mobile/WordPress-Android/pull/17584 — to ever happen again.
> Block WPAndroid PRs tagged as 'Not Ready for Merge'

- peril-settings.json
This should allow us to run the required Peril check when attempting a merge on `trunk` from the Merge Queue.
I set it up only for WordPress iOS because that's the repo where we are currently experimenting with merge queues. If this proves successful, we shall add it to other repos, too.
Also, I was tempted to extract the `ios-macos.ts` setting in a `"merge_group, pull_request"` entry, but didn't know how Peril would have behaved with the same event declared in multiple entries, so I left it as it was.
See:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
- https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/
> Add `merge_group` event listener to WordPress iOS repo

- README.md
- org/pr/ios-macos.ts
- tests/ios-podfile.test.ts
This PR tracks @AliSoftware's suggestions on top of #109.
GitHub reports the tests failing via its Checks, but when I select the [build](https://buildkite.com/automattic/peril-settings/builds/45), it 404s.
Interestingly, Buildkite can't find a `peril-settings` pipeline:
🤔 
[There's been an incident a couple of hours ago](https://www.buildkitestatus.com/incidents/t7hn25fb7fds), which _might_ have to do with this although it should have been resolved by now. I'll wait a bit and check again.
> Support nested dependencies from `Podfile.lock`
